<?xml version="1.0" encoding="utf-8"?><Database Name="QL_Duan" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WIN-EDAQ5ARTETT;Initial Catalog=QL_Duan;User ID=sa" SettingsObjectName="QL_Duan.Properties.Settings" SettingsPropertyName="QL_DuanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Thongtindonvi" Member="Thongtindonvis">
    <Type Name="Thongtindonvi">
      <Column Name="Madv" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tendonvi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Nguoidaidien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chucvu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sodienthoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nhanvien" Member="Nhanviens">
    <Type Name="Nhanvien">
      <Column Name="Manv" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tendangnhap" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Chucvu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Ngaysinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Hokhau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sodienthoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hinhanh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IDNhomquyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tinhtrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>